### ISSUE TITLE
why does lnprob return NaNs?

### ISSUE THREAD

**Issue by davidwhogg** [aimalz/prob-z#16] opened 2015-04-25 12:39 UTC
This can never happen.

**Comment by aimalz** [comment] 2015-04-27 21:22
The problem is the covariance matrix.  Though it is positive semi-definite, its determinant is something like 1e-168, effectively zero to within the precision of the calculation.  Since the determinant goes into the inverse, its inverse is not positive definite (whether computed numerically or symbolically) due to the limitations of floating point representation.  This broken inverse of course contributes to lnprob and propagates the floating point errors into the probabilities.

**Comment by davidwhogg** [comment] 2015-04-27 22:34
I don't understand this.

We aren't varying this covariance matrix, so it doesn't matter to the calculation, ever.  Or are we?  Anyway, in MCMC, we only need logpdf() to return something that is the log of the pdf up to a constant, so let's remove that constant.  And also remove the np.pi stuff too.

But I still don't understand.  The logdet of the matrix is a reasonable number even if the det is 1e-168.  Anyway, just drop this for now.

**Comment by davidwhogg** [comment] 2015-04-28 00:24
Oh wait -- is the inverse failing?  If so, let's just add some diagonal term to the covariance matrix to make the inverse safe.  This is standard practice for problems like this.  Figure out how to choose a safe value of "tiny" and do
    invcovar = inv(covar + diag(tiny))

**Comment by davidwhogg** [comment] 2015-04-28 00:42
ps we can discuss this and all other matters at CU tomorrow.

**Comment by aimalz** [comment] 2015-11-12 16:41
This hasn't been an issue in a long time so I'm closing it.

**Closed as completed by aimalz** 2015-11-12 16:41 UTC
Labels: high priority
